export const countryList = [
    { id: 1, name: "Afghanistan", code: "AF", phoneCode: "+93", flagEmoji: "🇦🇫" },
    { id: 2, name: "Albania", code: "AL", phoneCode: "+355", flagEmoji: "🇦🇱" },
    { id: 3, name: "Algeria", code: "DZ", phoneCode: "+213", flagEmoji: "🇩🇿" },
    { id: 4, name: "Andorra", code: "AD", phoneCode: "+376", flagEmoji: "🇦🇩" },
    { id: 5, name: "Angola", code: "AO", phoneCode: "+244", flagEmoji: "🇦🇴" },
    { id: 6, name: "Antigua and Barbuda", code: "AG", phoneCode: "+1-268", flagEmoji: "🇦🇬" },
    { id: 7, name: "Argentina", code: "AR", phoneCode: "+54", flagEmoji: "🇦🇷" },
    { id: 8, name: "Armenia", code: "AM", phoneCode: "+374", flagEmoji: "🇦🇲" },
    { id: 9, name: "Australia", code: "AU", phoneCode: "+61", flagEmoji: "🇦🇺" },
    { id: 10, name: "Austria", code: "AT", phoneCode: "+43", flagEmoji: "🇦🇹" },
    { id: 11, name: "Azerbaijan", code: "AZ", phoneCode: "+994", flagEmoji: "🇦🇿" },
    { id: 12, name: "Bahamas", code: "BS", phoneCode: "+1-242", flagEmoji: "🇧🇸" },
    { id: 13, name: "Bahrain", code: "BH", phoneCode: "+973", flagEmoji: "🇧🇭" },
    { id: 14, name: "Bangladesh", code: "BD", phoneCode: "+880", flagEmoji: "🇧🇩" },
    { id: 15, name: "Barbados", code: "BB", phoneCode: "+1-246", flagEmoji: "🇧🇧" },
    { id: 16, name: "Belarus", code: "BY", phoneCode: "+375", flagEmoji: "🇧🇾" },
    { id: 17, name: "Belgium", code: "BE", phoneCode: "+32", flagEmoji: "🇧🇪" },
    { id: 18, name: "Belize", code: "BZ", phoneCode: "+501", flagEmoji: "🇧🇿" },
    { id: 19, name: "Benin", code: "BJ", phoneCode: "+229", flagEmoji: "🇧🇯" },
    { id: 20, name: "Bhutan", code: "BT", phoneCode: "+975", flagEmoji: "🇧🇹" },
    { id: 21, name: "Bolivia", code: "BO", phoneCode: "+591", flagEmoji: "🇧🇴" },
    { id: 22, name: "Bosnia and Herzegovina", code: "BA", phoneCode: "+387", flagEmoji: "🇧🇦" },
    { id: 23, name: "Botswana", code: "BW", phoneCode: "+267", flagEmoji: "🇧🇼" },
    { id: 24, name: "Brazil", code: "BR", phoneCode: "+55", flagEmoji: "🇧🇷" },
    { id: 25, name: "Brunei", code: "BN", phoneCode: "+673", flagEmoji: "🇧🇳" },
    { id: 26, name: "Bulgaria", code: "BG", phoneCode: "+359", flagEmoji: "🇧🇬" },
    { id: 27, name: "Burkina Faso", code: "BF", phoneCode: "+226", flagEmoji: "🇧🇫" },
    { id: 28, name: "Burundi", code: "BI", phoneCode: "+257", flagEmoji: "🇧🇮" },
    { id: 29, name: "Cabo Verde", code: "CV", phoneCode: "+238", flagEmoji: "🇨🇻" },
    { id: 30, name: "Cambodia", code: "KH", phoneCode: "+855", flagEmoji: "🇰🇭" },
    { id: 31, name: "Cameroon", code: "CM", phoneCode: "+237", flagEmoji: "🇨🇲" },
    { id: 32, name: "Canada", code: "CA", phoneCode: "+1", flagEmoji: "🇨🇦" },
    { id: 33, name: "Central African Republic", code: "CF", phoneCode: "+236", flagEmoji: "🇨🇫" },
    { id: 34, name: "Chad", code: "TD", phoneCode: "+235", flagEmoji: "🇹🇩" },
    { id: 35, name: "Chile", code: "CL", phoneCode: "+56", flagEmoji: "🇨🇱" },
    { id: 36, name: "China", code: "CN", phoneCode: "+86", flagEmoji: "🇨🇳" },
    { id: 37, name: "Colombia", code: "CO", phoneCode: "+57", flagEmoji: "🇨🇴" },
    { id: 38, name: "Comoros", code: "KM", phoneCode: "+269", flagEmoji: "🇰🇲" },
    { id: 39, name: "Congo (Congo-Brazzaville)", code: "CG", phoneCode: "+242", flagEmoji: "🇨🇬" },
    { id: 40, name: "Congo (Democratic Republic)", code: "CD", phoneCode: "+243", flagEmoji: "🇨🇩" },
    { id: 41, name: "Costa Rica", code: "CR", phoneCode: "+506", flagEmoji: "🇨🇷" },
    { id: 42, name: "Croatia", code: "HR", phoneCode: "+385", flagEmoji: "🇭🇷" },
    { id: 43, name: "Cuba", code: "CU", phoneCode: "+53", flagEmoji: "🇨🇺" },
    { id: 44, name: "Cyprus", code: "CY", phoneCode: "+357", flagEmoji: "🇨🇾" },
    { id: 45, name: "Czech Republic", code: "CZ", phoneCode: "+420", flagEmoji: "🇨🇿" },
    { id: 46, name: "Denmark", code: "DK", phoneCode: "+45", flagEmoji: "🇩🇰" },
    { id: 47, name: "Djibouti", code: "DJ", phoneCode: "+253", flagEmoji: "🇩🇯" },
    { id: 48, name: "Dominica", code: "DM", phoneCode: "+1-767", flagEmoji: "🇩🇲" },
    { id: 49, name: "Dominican Republic", code: "DO", phoneCode: "+1-809", flagEmoji: "🇩🇴" },
    { id: 50, name: "Ecuador", code: "EC", phoneCode: "+593", flagEmoji: "🇪🇨" },
    { id: 51, name: "Egypt", code: "EG", phoneCode: "+20", flagEmoji: "🇪🇬" },
    { id: 52, name: "El Salvador", code: "SV", phoneCode: "+503", flagEmoji: "🇸🇻" },
    { id: 53, name: "Equatorial Guinea", code: "GQ", phoneCode: "+240", flagEmoji: "🇬🇶" },
    { id: 54, name: "Eritrea", code: "ER", phoneCode: "+291", flagEmoji: "🇪🇷" },
    { id: 55, name: "Estonia", code: "EE", phoneCode: "+372", flagEmoji: "🇪🇪" },
    { id: 56, name: "Eswatini", code: "SZ", phoneCode: "+268", flagEmoji: "🇸🇿" },
    { id: 57, name: "Ethiopia", code: "ET", phoneCode: "+251", flagEmoji: "🇪🇹" },
    { id: 58, name: "Fiji", code: "FJ", phoneCode: "+679", flagEmoji: "🇫🇯" },
    { id: 59, name: "Finland", code: "FI", phoneCode: "+358", flagEmoji: "🇫🇮" },
    { id: 60, name: "France", code: "FR", phoneCode: "+33", flagEmoji: "🇫🇷" },
    { id: 61, name: "Gabon", code: "GA", phoneCode: "+241", flagEmoji: "🇬🇦" },
    { id: 62, name: "Gambia", code: "GM", phoneCode: "+220", flagEmoji: "🇬🇲" },
    { id: 63, name: "Georgia", code: "GE", phoneCode: "+995", flagEmoji: "🇬🇪" },
    { id: 64, name: "Germany", code: "DE", phoneCode: "+49", flagEmoji: "🇩🇪" },
    { id: 65, name: "Ghana", code: "GH", phoneCode: "+233", flagEmoji: "🇬🇭" },
    { id: 66, name: "Greece", code: "GR", phoneCode: "+30", flagEmoji: "🇬🇷" },
    { id: 67, name: "Grenada", code: "GD", phoneCode: "+1-473", flagEmoji: "🇬🇩" },
    { id: 68, name: "Guatemala", code: "GT", phoneCode: "+502", flagEmoji: "🇬🇹" },
    { id: 69, name: "Guinea", code: "GN", phoneCode: "+224", flagEmoji: "🇬🇳" },
    { id: 70, name: "Guinea-Bissau", code: "GW", phoneCode: "+245", flagEmoji: "🇬🇼" },
    { id: 71, name: "Guyana", code: "GY", phoneCode: "+592", flagEmoji: "🇬🇾" },
    { id: 72, name: "Haiti", code: "HT", phoneCode: "+509", flagEmoji: "🇭🇹" },
    { id: 73, name: "Honduras", code: "HN", phoneCode: "+504", flagEmoji: "🇭🇳" },
    { id: 74, name: "Hungary", code: "HU", phoneCode: "+36", flagEmoji: "🇭🇺" },
    { id: 75, name: "Iceland", code: "IS", phoneCode: "+354", flagEmoji: "🇮🇸" },
    { id: 76, name: "India", code: "IN", phoneCode: "+91", flagEmoji: "🇮🇳" },
    { id: 77, name: "Indonesia", code: "ID", phoneCode: "+62", flagEmoji: "🇮🇩" },
    { id: 78, name: "Iran", code: "IR", phoneCode: "+98", flagEmoji: "🇮🇷" },
    { id: 79, name: "Iraq", code: "IQ", phoneCode: "+964", flagEmoji: "🇮🇶" },
    { id: 80, name: "Ireland", code: "IE", phoneCode: "+353", flagEmoji: "🇮🇪" },
    { id: 81, name: "Israel", code: "IL", phoneCode: "+972", flagEmoji: "🇮🇱" },
    { id: 82, name: "Italy", code: "IT", phoneCode: "+39", flagEmoji: "🇮🇹" },
    { id: 83, name: "Jamaica", code: "JM", phoneCode: "+1-876", flagEmoji: "🇯🇲" },
    { id: 84, name: "Japan", code: "JP", phoneCode: "+81", flagEmoji: "🇯🇵" },
    { id: 85, name: "Jordan", code: "JO", phoneCode: "+962", flagEmoji: "🇯🇴" },
    { id: 86, name: "Kazakhstan", code: "KZ", phoneCode: "+7", flagEmoji: "🇰🇿" },
    { id: 87, name: "Kenya", code: "KE", phoneCode: "+254", flagEmoji: "🇰🇪" },
    { id: 88, name: "Kiribati", code: "KI", phoneCode: "+686", flagEmoji: "🇰🇮" },
    { id: 89, name: "Korea (North)", code: "KP", phoneCode: "+850", flagEmoji: "🇰🇵" },
    { id: 90, name: "Korea (South)", code: "KR", phoneCode: "+82", flagEmoji: "🇰🇷" },
    { id: 91, name: "Kuwait", code: "KW", phoneCode: "+965", flagEmoji: "🇰🇼" },
    { id: 92, name: "Kyrgyzstan", code: "KG", phoneCode: "+996", flagEmoji: "🇰🇬" },
    { id: 93, name: "Laos", code: "LA", phoneCode: "+856", flagEmoji: "🇱🇦" },
    { id: 94, name: "Latvia", code: "LV", phoneCode: "+371", flagEmoji: "🇱🇻" },
    { id: 95, name: "Lebanon", code: "LB", phoneCode: "+961", flagEmoji: "🇱🇧" },
    { id: 96, name: "Lesotho", code: "LS", phoneCode: "+266", flagEmoji: "🇱🇸" },
    { id: 97, name: "Liberia", code: "LR", phoneCode: "+231", flagEmoji: "🇱🇷" },
    { id: 98, name: "Libya", code: "LY", phoneCode: "+218", flagEmoji: "🇱🇾" },
    { id: 99, name: "Liechtenstein", code: "LI", phoneCode: "+423", flagEmoji: "🇱🇮" },
    { id: 100, name: "Lithuania", code: "LT", phoneCode: "+370", flagEmoji: "🇱🇹" },
    { id: 101, name: "Luxembourg", code: "LU", phoneCode: "+352", flagEmoji: "🇱🇺" },
    { id: 102, name: "Madagascar", code: "MG", phoneCode: "+261", flagEmoji: "🇲🇬" },
    { id: 103, name: "Malawi", code: "MW", phoneCode: "+265", flagEmoji: "🇲🇼" },
    { id: 104, name: "Malaysia", code: "MY", phoneCode: "+60", flagEmoji: "🇲🇾" },
    { id: 105, name: "Maldives", code: "MV", phoneCode: "+960", flagEmoji: "🇲🇻" },
    { id: 106, name: "Mali", code: "ML", phoneCode: "+223", flagEmoji: "🇲🇱" },
    { id: 107, name: "Malta", code: "MT", phoneCode: "+356", flagEmoji: "🇲🇹" },
    { id: 108, name: "Marshall Islands", code: "MH", phoneCode: "+692", flagEmoji: "🇲🇭" },
    { id: 109, name: "Mauritania", code: "MR", phoneCode: "+222", flagEmoji: "🇲🇷" },
    { id: 110, name: "Mauritius", code: "MU", phoneCode: "+230", flagEmoji: "🇲🇺" },
    { id: 111, name: "Mexico", code: "MX", phoneCode: "+52", flagEmoji: "🇲🇽" },
    { id: 112, name: "Micronesia", code: "FM", phoneCode: "+691", flagEmoji: "🇫🇲" },
    { id: 113, name: "Moldova", code: "MD", phoneCode: "+373", flagEmoji: "🇲🇩" },
    { id: 114, name: "Monaco", code: "MC", phoneCode: "+377", flagEmoji: "🇲🇨" },
    { id: 115, name: "Mongolia", code: "MN", phoneCode: "+976", flagEmoji: "🇲🇳" },
    { id: 116, name: "Montenegro", code: "ME", phoneCode: "+382", flagEmoji: "🇲🇪" },
    { id: 117, name: "Morocco", code: "MA", phoneCode: "+212", flagEmoji: "🇲🇦" },
    { id: 118, name: "Mozambique", code: "MZ", phoneCode: "+258", flagEmoji: "🇲🇿" },
    { id: 119, name: "Myanmar (Burma)", code: "MM", phoneCode: "+95", flagEmoji: "🇲🇲" },
    { id: 120, name: "Namibia", code: "NA", phoneCode: "+264", flagEmoji: "🇳🇦" },
    { id: 121, name: "Nauru", code: "NR", phoneCode: "+674", flagEmoji: "🇳🇷" },
    { id: 122, name: "Nepal", code: "NP", phoneCode: "+977", flagEmoji: "🇳🇵" },
    { id: 123, name: "Netherlands", code: "NL", phoneCode: "+31", flagEmoji: "🇳🇱" },
    { id: 124, name: "New Zealand", code: "NZ", phoneCode: "+64", flagEmoji: "🇳🇿" },
    { id: 125, name: "Nicaragua", code: "NI", phoneCode: "+505", flagEmoji: "🇳🇮" },
    { id: 126, name: "Niger", code: "NE", phoneCode: "+227", flagEmoji: "🇳🇪" },
    { id: 127, name: "Nigeria", code: "NG", phoneCode: "+234", flagEmoji: "🇳🇬" },
    { id: 128, name: "North Macedonia", code: "MK", phoneCode: "+389", flagEmoji: "🇲🇰" },
    { id: 129, name: "Norway", code: "NO", phoneCode: "+47", flagEmoji: "🇳🇴" },
    { id: 130, name: "Oman", code: "OM", phoneCode: "+968", flagEmoji: "🇴🇲" },
    { id: 131, name: "Pakistan", code: "PK", phoneCode: "+92", flagEmoji: "🇵🇰" },
    { id: 132, name: "Palau", code: "PW", phoneCode: "+680", flagEmoji: "🇵🇼" },
    { id: 133, name: "Panama", code: "PA", phoneCode: "+507", flagEmoji: "🇵🇦" },
    { id: 134, name: "Papua New Guinea", code: "PG", phoneCode: "+675", flagEmoji: "🇵🇬" },
    { id: 135, name: "Paraguay", code: "PY", phoneCode: "+595", flagEmoji: "🇵🇾" },
    { id: 136, name: "Peru", code: "PE", phoneCode: "+51", flagEmoji: "🇵🇪" },
    { id: 137, name: "Philippines", code: "PH", phoneCode: "+63", flagEmoji: "🇵🇭" },
    { id: 138, name: "Poland", code: "PL", phoneCode: "+48", flagEmoji: "🇵🇱" },
    { id: 139, name: "Portugal", code: "PT", phoneCode: "+351", flagEmoji: "🇵🇹" },
    { id: 140, name: "Qatar", code: "QA", phoneCode: "+974", flagEmoji: "🇶🇦" },
    { id: 141, name: "Romania", code: "RO", phoneCode: "+40", flagEmoji: "🇷🇴" },
    { id: 142, name: "Russia", code: "RU", phoneCode: "+7", flagEmoji: "🇷🇺" },
    { id: 143, name: "Rwanda", code: "RW", phoneCode: "+250", flagEmoji: "🇷🇼" },
    { id: 144, name: "Saint Kitts and Nevis", code: "KN", phoneCode: "+1-869", flagEmoji: "🇰🇳" },
    { id: 145, name: "Saint Lucia", code: "LC", phoneCode: "+1-758", flagEmoji: "🇱🇨" },
    { id: 146, name: "Saint Vincent and the Grenadines", code: "VC", phoneCode: "+1-784", flagEmoji: "🇻🇨" },
    { id: 147, name: "Samoa", code: "WS", phoneCode: "+685", flagEmoji: "🇼🇸" },
    { id: 148, name: "San Marino", code: "SM", phoneCode: "+378", flagEmoji: "🇸🇲" },
    { id: 149, name: "Sao Tome and Principe", code: "ST", phoneCode: "+239", flagEmoji: "🇸🇹" },
    { id: 150, name: "Saudi Arabia", code: "SA", phoneCode: "+966", flagEmoji: "🇸🇦" },
    { id: 151, name: "Senegal", code: "SN", phoneCode: "+221", flagEmoji: "🇸🇳" },
  { id: 152, name: "Serbia", code: "RS", phoneCode: "+381", flagEmoji: "🇷🇸" },
  { id: 153, name: "Seychelles", code: "SC", phoneCode: "+248", flagEmoji: "🇸🇨" },
  { id: 154, name: "Sierra Leone", code: "SL", phoneCode: "+232", flagEmoji: "🇸🇱" },
  { id: 155, name: "Singapore", code: "SG", phoneCode: "+65", flagEmoji: "🇸🇬" },
  { id: 156, name: "Slovakia", code: "SK", phoneCode: "+421", flagEmoji: "🇸🇰" },
  { id: 157, name: "Slovenia", code: "SI", phoneCode: "+386", flagEmoji: "🇸🇮" },
  { id: 158, name: "Solomon Islands", code: "SB", phoneCode: "+677", flagEmoji: "🇸🇧" },
  { id: 159, name: "Somalia", code: "SO", phoneCode: "+252", flagEmoji: "🇸🇴" },
  { id: 160, name: "South Africa", code: "ZA", phoneCode: "+27", flagEmoji: "🇿🇦" },
  { id: 161, name: "South Sudan", code: "SS", phoneCode: "+211", flagEmoji: "🇸🇸" },
  { id: 162, name: "Spain", code: "ES", phoneCode: "+34", flagEmoji: "🇪🇸" },
  { id: 163, name: "Sri Lanka", code: "LK", phoneCode: "+94", flagEmoji: "🇱🇰" },
  { id: 164, name: "Sudan", code: "SD", phoneCode: "+249", flagEmoji: "🇸🇩" },
  { id: 165, name: "Suriname", code: "SR", phoneCode: "+597", flagEmoji: "🇸🇷" },
  { id: 166, name: "Sweden", code: "SE", phoneCode: "+46", flagEmoji: "🇸🇪" },
  { id: 167, name: "Switzerland", code: "CH", phoneCode: "+41", flagEmoji: "🇨🇭" },
  { id: 168, name: "Syria", code: "SY", phoneCode: "+963", flagEmoji: "🇸🇾" },
  { id: 169, name: "Taiwan", code: "TW", phoneCode: "+886", flagEmoji: "🇹🇼" },
  { id: 170, name: "Tajikistan", code: "TJ", phoneCode: "+992", flagEmoji: "🇹🇯" },
  { id: 171, name: "Tanzania", code: "TZ", phoneCode: "+255", flagEmoji: "🇹🇿" },
  { id: 172, name: "Thailand", code: "TH", phoneCode: "+66", flagEmoji: "🇹🇭" },
  { id: 173, name: "Timor-Leste", code: "TL", phoneCode: "+670", flagEmoji: "🇹🇱" },
  { id: 174, name: "Togo", code: "TG", phoneCode: "+228", flagEmoji: "🇹🇬" },
  { id: 175, name: "Tonga", code: "TO", phoneCode: "+676", flagEmoji: "🇹🇴" },
  { id: 176, name: "Trinidad and Tobago", code: "TT", phoneCode: "+1-868", flagEmoji: "🇹🇹" },
  { id: 177, name: "Tunisia", code: "TN", phoneCode: "+216", flagEmoji: "🇹🇳" },
  { id: 178, name: "Turkey", code: "TR", phoneCode: "+90", flagEmoji: "🇹🇷" },
  { id: 179, name: "Turkmenistan", code: "TM", phoneCode: "+993", flagEmoji: "🇹🇲" },
  { id: 180, name: "Tuvalu", code: "TV", phoneCode: "+688", flagEmoji: "🇹🇻" },
  { id: 181, name: "Uganda", code: "UG", phoneCode: "+256", flagEmoji: "🇺🇬" },
  { id: 182, name: "Ukraine", code: "UA", phoneCode: "+380", flagEmoji: "🇺🇦" },
  { id: 183, name: "United Arab Emirates", code: "AE", phoneCode: "+971", flagEmoji: "🇦🇪" },
  { id: 184, name: "United Kingdom", code: "GB", phoneCode: "+44", flagEmoji: "🇬🇧" },
  { id: 185, name: "United States", code: "US", phoneCode: "+1", flagEmoji: "🇺🇸" },
  { id: 186, name: "Uruguay", code: "UY", phoneCode: "+598", flagEmoji: "🇺🇾" },
  { id: 187, name: "Uzbekistan", code: "UZ", phoneCode: "+998", flagEmoji: "🇺🇿" },
  { id: 188, name: "Vanuatu", code: "VU", phoneCode: "+678", flagEmoji: "🇻🇺" },
  { id: 189, name: "Vatican City", code: "VA", phoneCode: "+379", flagEmoji: "🇻🇦" },
  { id: 190, name: "Venezuela", code: "VE", phoneCode: "+58", flagEmoji: "🇻🇪" },
  { id: 191, name: "Vietnam", code: "VN", phoneCode: "+84", flagEmoji: "🇻🇳" },
  { id: 192, name: "Yemen", code: "YE", phoneCode: "+967", flagEmoji: "🇾🇪" },
  { id: 193, name: "Zambia", code: "ZM", phoneCode: "+260", flagEmoji: "🇿🇲" },
  { id: 194, name: "Zimbabwe", code: "ZW", phoneCode: "+263", flagEmoji: "🇿🇼" },
  
  


];
  